[package]
name = "neural_network_example"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.5.1"
linfa-datasets = { version = "0.5.1", features = ["iris"] }
linfa-trees = "0.5.1"
ndarray = "0.15"
