[package]
name = "neural_network_example"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.7.0"
linfa-datasets = { version = "0.7.0", features = ["diabetes"] }
linfa-trees = "0.7.0"
ndarray = "0.15"
rand = "0.8"
